- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create mysql user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
